services:
  - type: web
    name: sipakjag
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    env: python
    region: singapore
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
